### ISSUE TITLE
How to set default field values?

### ISSUE THREAD

**Issue by sebastianlenton** [area17/twill#114]
Hi,

When a user creates a record I would like some form fields to have default values. How do I do this?

Also, is it possible to set the "Draft/Live" toggle default to "live" instead of "draft" when creating new records?

Thanks!

**Comment by ifox** [comment]
Hi Seb,

There are many ways to deal with this, like database default constraints or Laravel model events or mutators, but the "Twill way" would be to use the `prepareFieldsBeforeCreate` hook in your module's repository:

```php
public function prepareFieldsBeforeCreate($fields) {
    // set default values in fields here
    return parent::prepareFieldsBeforeCreate($fields);
}
```

It is not possible to set the "Draft/Live" toggle default to "live" right now, but should be fairly simple to implement as an option!

**Comment by sebastianlenton** [comment]
Thanks, I got that working on "normal" fields, but how do I add defaults for fields in blocks?

BTW re the draft/live toggle, it would be nice to be able to default it to live and then hide the switch, as certain module types might not need to be settable as draft. But it's not really a problem, just wondering.

**Comment by ifox** [comment]
Depending on the form field type you are looking to set a default value for, you might be able to do it at the `@formField` declaration.  The `select`, `radios` and `checkbox` fields support a `default` option to automatically set a default value on block creation. For other fields you might have to modify the submitted fields in the `prepareFieldsBeforeSave` hook, but let me know your exact use case!

**Comment by sebastianlenton** [comment]
Unfortunately it's for a text input inside a block- ideally there needs to be a default value there when creating a new record.

**Comment by sebastianlenton** [comment]
Hi,

Still wondering if this is possible? To reiterate, my use-case is as follows:

I have text fields within blocks that need a default value on creation.

Unless I'm misunderstanding, the `prepareFieldsBeforeSave` hook isn't a good fit for this, as the client wants there to be a default value from the beginning, and also I found I have to disable validation on these fields in order for `prepareFieldsBeforeSave` to fire.

(This is indirectly related to https://github.com/area17/twill/issues/109- I can't seem to get these same fields to highlight in red if they're invalid. I need them to have a default value plus a visual indication if invalid.)

Thanks as ever!

**Comment by ifox** [comment]
Hi Seb,

This is not possible right now but should not be a problem to implement as we already support it on a couple of fields.

Validation is executed before anything else so you'd have to use hidden fields to submit some default content that needs validation, but I'm struggling to see a use case for that. Maybe a dynamic hidden field value would need that, as a way to prevent saving a record if some sort of dependency is not valid. 

I'm just thinking out loud here, but to get back to your use case where you actually wouldn't hit issues validation those default values of course, I'll take a look tomorrow at supporting a default option in the input form field.

Regarding #109, I owe you an answer there, sorry for the delay. It's not that you are doing it wrong, it's that we have to patch the default validation system response for block inputs validation highlight to work and that happens through a custom validation rule for blocks, that pull rules from the blocks configuration in `twill.php` so that you do not have to repeat the rules in all forms that use the same blocks. I'll reply on #109 with more info tomorrow.

**Comment by ifox** [comment]
Default values are now supported in input fields like they are in select and other fields @sebastianlenton.

```
@formField('input', [
    'name' => 'fieldName',
    'label' => ' Field label',
    'default' => 'default value'
])
```

I still owe you an answer on #109 and will make sure to prioritize it now that 1.2.1 is out!
