### ISSUE TITLE
Getting the Content Editor to work

### ISSUE THREAD

**Issue by sebastianlenton** [area17/twill#116]
Hi,

Can you provide some info on getting the Content Editor to work? I created the site/layouts/block.blade.php file but I don't know what to do from this point.

Thanks

**Comment by ifox** [comment]
Hi Seb,

The block layout should yield a `content` section: `@yield('content')`. You are free to wrap it with the markup that makes sense to your setup. The layout should of course include the CSS/JS that is loaded in your main frontend layout as well. You can create a shared layout to avoid duplicating code. 

You can also specify a custom layout view using `twill.block_editor.block_single_layout` and a custom blocks views path using `twill.block_editor.block_views_path`.

If you used renderBlocks in the frontend already, your content editor should be working directly once you setup the single block layout correctly.

**Comment by sebastianlenton** [comment]
Thanks, I didn't realise it would be as simple as that! However, I've now got another problem- I notice each block is inside an iframe, but that breaks the layout (eg they can't float next to each other as they would normally). Is there anything I can do about this, and if not is it possible to disable the content editor button?

**Comment by ifox** [comment]
I see. Are you using a repeater inside a block to render some kind of grid of items in the frontend? 

In that case, you can opt-out from rendering children blocks (repeater items) as separate blocks (and consequently iframe) using `twill.block_editor.block_preview_render_childs`. Inside the parent block, you can access the repeater items using `children` on the `$block` variable.

If your issue is more related to a composition you created on the frontend not being linear, by that I mean with blocks not just being displayed one after the other, I can see how the content editor experience can be confusing, but I'm very eager to chat more about this as we would definitely like to support more use cases there.

You can disable the main editor button in the form using `'editor' => false` when extending the form layout, or using `protected $disableEditor = true;` in the module's controller.

**Comment by nsivertsen** [comment]
I would also be very interested in something like this. My use case is an Article module where blocks (text, quotes, images, galleries, ...) are rendered inside a CSS grid container and every block has some layout parameters:

- column span
- offset
- alignment
- justification

... that affect its placement in the grid. As it currently stands, it's impossible to get that layout in the block editor—they stack up one on top of the other. I'm not sure there is an easy way of fixing this; maybe blocks could somehow declare CSS classes that are passed on to the iframe?

**Comment by sebastianlenton** [comment]
My use case sounds similar to @nsivertsen's.

Each "content preview" block added to the record has a browser scope (for the content) and a column width field. Inside the block's frontend blade file the width is added as a CSS class, and they all more or less get floated to the left.

In order to get the content editor to work with my layout, I guess each iframe would need the same layout markup as I'm using for the frontend layout, and in addition when a width gets changed the entire contents of the parent container (around all the blocks/iframes) would also need to be updated in order for the layout to render correctly.

**Comment by ifox** [comment]
All making sense guys, thanks for sharing more about your setup and needs. As of now I hear you that the content editor is not working great for non-linear layouts. One way we implemented similar concerns was to use a repeater inside a block, and render those repeaters all in the same parent block, so that the preview iframe shows the full module, and grid layouts are not a problem. But it's definitely not necessarily a viable solution if the idea is to display different blocks as a grid. However, I think it would be possible to figure out a solution by allowing custom classes to be added to each iframes, as well as their wrapper element, yes, so let's keep discussing and experimenting here!

**Comment by ifox** [comment]
I meant different classes for the block and wrapper, for sure.

It would definitely help to build a repeater that allows multiple types of blocks, which basically mean a block editor inside a block editor :)

Not completely related, but take a look at #112 where @m4n1ok has been working on supporting multiple block editors in the same form, which is also going to help in some situations.

**Comment by nsivertsen** [comment]
I guess what I mean is that in that case, blocks would have to "know" whether they are being rendered in the block editor or not, because certain classes (those pertaining to layout) shouldn't be applied when they are. But I guess that is not that great of an evil for the benefits that would bring. Designing grid-based content and seeing it reflow before your eyes when you change parameters would be pretty great.

Yeah, I saw that, I'm very excited about that! Twill is improving by leaps and bounds!
