### ISSUE TITLE
Media File Could not be able to deleted

### ISSUE THREAD

**Issue by venkataadithan** [area17/twill#1160]
## Description

Media File Could not be able to deleted, when with an polymorphic relation association with the soft deleted records..

### Steps to reproduce
1) Add media file to media library
2) Create a new record in any module ex:Blog
3) Associate the media file to the blog.
4) Soft Delete the blog with deleted_at column on.
5) Now try to delete the media file, delete option is not enabled.

### Expected result

Media file should be deleted after checking the soft deleted colum is null or not.

### Actual result

Media File Could not be deleted. 

### Versions

Twill version:  2.3.1
Laravel version: 6.20.34
PHP version: 7.4.23
Database engine: mySql

**Comment by pboivin** [comment]
Hi @venkataadithan, I can confirm this issue, thanks for reporting!

Just to clarify, it seems normal to me that I can't delete an image associated with a soft delete record. I may restore this record eventually and the image should be restored with it. Although the problem also happens when I permanently delete the record. Then, the image also can't be deleted, which is not desirable.

Does this make sense? Is this what you are experiencing?

**Comment by ifox** [comment]
Hi both. This behavior is definitely on purpose, for the reason you identified @pboivin. However, after destroying a soft deleted record from the UI, the relationship to the media should be destroyed as well which would let the user delete the image in the media library.

**Comment by pboivin** [comment]
@ifox I ran a few more tests on my end. When destroying a soft deleted record from the UI, it looks like the corresponding records from the `mediables` table are not deleted with it. Am I missing something obvious?

**Comment by venkataadithan** [comment]
This is the issue here @pboivin both softDelete and Destroy function checks only canDeleteSafely method on mediables or fileables.

This **canDeleteSafely** method didn't check mediable against the deleted records.
