### ISSUE TITLE
Use config subfolder for Twill

### ISSUE THREAD

**Issue by yanhao-li** [area17/twill#118]
Currently the two config files Twill will publish are` config/twill.php` and `config/twill-navigation.php`. 

The problem is `config/twill.php` contains too many settings inside it, and will easily grows very large, even over 1000 lines sometimes, so as to become less manageable and easily to make mistake.

I'm thinking is that possible to make a subfolder inside laravel config folder, named twill, which will contain all twill-related setting files, ex. `config.twill.medialibrary`,  `config.twill.navigation`, `config.twill.blockeditor`. In this way, it will have a better organization and be eaiser to manage.

**Comment by ifox** [comment]
Laravel supports dot notation to access config in subfolders, so I tend to think this should already work, just give it a try! `config/twill/block_editor.php` returning the value of the `block_editor` key you currently have in `config/twill.php` should work I guess.

If it does, we can support moving the navigation under `twill.navigation` instead of `twill-navigation`.

**Comment by zipavlin** [comment]
> Laravel supports dot notation to access config in subfolders, so I tend to think this should already work, just give it a try! `config/twill/block_editor.php` returning the value of the `block_editor` key you currently have in `config/twill.php` should work I guess.
> 
> If it does, we can support moving the navigation under `twill.navigation` instead of `twill-navigation`.

I just tried it and it seems to be working! 👍
