### ISSUE TITLE
Unable to get past the initial setup

### ISSUE THREAD

**Issue by codeace** [area17/twill#12]
Symfony\Component\Debug\Exception\FatalErrorException  : Cannot declare class CreateActivityLogTable, because the name is already in use

**Comment by DeanWard** [comment]
I managed to pass that error by deleting all the migrations in the migrations folder.

**Comment by ifox** [comment]
Hi Frank, thanks for reporting your issue!

I noticed this happens when your application already have one of Twill's dependencies and how the initial setup can be destructive to an existing application in #11.

I am going to work on documentation updates as well as some refactoring to be more sensitive to existing applications, stay tuned!

**Comment by DeanWard** [comment]
@ifox I cam across this issue on a fresh Laravel app when I initially miss-configured the database and the migration failed. It looks like the setup script creates the migrations regardless of how many times they have already been created.

**Comment by ifox** [comment]
You are right @DeanWard! 

Thanks for providing context, really helpful and going to help us making the setup script more friendly to use by fixing those issues!

**Comment by freeyland** [comment]
When doing php artisan twill:install =>
PHP Fatal error:  Cannot declare class CreateActivityLogTable, because the name is already in use in /var/www/twill/database/migrations/2019_02_05_112813_create_activity_log_table.php on line 36
