### ISSUE TITLE
Media library - possible to create folders?

### ISSUE THREAD

**Issue by sebastianlenton** [area17/twill#121]
Hi,

Is it possible to create folders in the media library, to better organise content? My client has asked re this.

Thanks!

**Comment by ifox** [comment]
Hi Seb,

folders are not supported in the media library, however we suggest using tags as a way to organize content. You can use shift to select multiple images and tag them in bulk. When editing content on a form, the media library keeps the current search or tags applied even after being closed, since you most likely want to work with the same results.

**Comment by sebastianlenton** [comment]
Makes sense- thanks again!
