### ISSUE TITLE
Best way to lock down admin?

### ISSUE THREAD

**Issue by nikhiltri** [area17/twill#137]
Hello!

On an instance of Twill that serves both the frontend and the admin, what's the best way to restrict access to the admin more rigorously, like by IP address? Would it be to point the ADMIN_APP_URL to an instance running on a different server that you lock down more than the frontend? Or are there better ways to do it?

Thanks!
nikhil

**Comment by ifox** [comment]
Hi @nikhiltri!

That's definitely an option. We tend to keep a simple HTTP authentication on the admin subdomain, but I can understand how this could not be a perfect user experience for editors.

What about whitelisting IPs at the web server level? You'd have to separate admin and frontend location definition in your Nginx configuration for example.

Another solution would be at the application level using a package like https://github.com/antonioribeiro/firewall, since Twill allows you to set a custom middleware group for the admin domain using `admin_middleware_group` in `twill.php`, which default to `web`.

**Comment by nikhiltri** [comment]
We'll take a look at those suggestions. Thanks!
