### ISSUE TITLE
error message during setup - asset path?

### ISSUE THREAD

**Issue by kelenakamura** [area17/twill#14]
php artisan twill:setup

Can't locate path: </Users/XXX/Twill/repos/vendor/area17/twill/src/../assets>
Publishing complete.

not sure what this is supposed to be doing anything i can do manually to resolve?

thanks Kele.

**Comment by diegonelson** [comment]
I have the same error!

**Comment by ifox** [comment]
Hi @kelenakamura and @diegonelson! 

Interesting, this seem to be related to running on Windows, for which I'll be honest and say we did not really test for but are happy to do since there seem to be some issues we weren't aware of!

However the code causing this has no reason to exist anymore at this stage, this is coming from older releases of Twill where assets were static and simply published instead of being provided as NPM scripts to build yourself.

Here it is:
https://github.com/area17/twill/blob/4d58468db4c2aec3bcbb7ed8c8de3dfb78c5240b/src/Commands/Setup.php#L53-L59

Which triggers the following:
https://github.com/area17/twill/blob/4d58468db4c2aec3bcbb7ed8c8de3dfb78c5240b/src/TwillServiceProvider.php#L225-L228

Both of those could be completely removed as the assets folder does not exist anymore. Feel free to submit a PR and we'll release a new version, otherwise I will take care of this as soon as possible. You can manually remove the following line in your project in the meantime if you want to keep testing for now:
https://github.com/area17/twill/blob/4d58468db4c2aec3bcbb7ed8c8de3dfb78c5240b/src/Commands/Setup.php#L18

**Comment by kelenakamura** [comment]
just for clarification. i'm on mac, not windows.

all i did was follow you install instructions, so maybe the package on npm is out of date?

composer require area17/twill

"area17/twill": "^1.1",

is this the wrong version?

thanks Kele.

**Comment by ifox** [comment]
You have the right version @kelenakamura, all I'm saying is that this is actually a "bug" in Twill's setup command. I wrongly assumed you were running on Windows because I did not encounter this error when running on OSX or Unix and it doesn't look like other users did either.

**Comment by ifox** [comment]
Actually, I'm able to reproduce too as well as @noxify.

Please ignore this error message, it doesn't affect the setup process. I'm going to fix the command as defined [above](https://github.com/area17/twill/issues/14#issuecomment-405340651) in our next release. Can you confirm the command continued and exited properly after this message?
