### ISSUE TITLE
Uncaught TypeError: window.TWILL.STORE.config is undefined

### ISSUE THREAD

**Issue by michaeljcoyne** [area17/twill#1490]
## Description

Locally I dont get this issue

### Steps to reproduce

Building twill for production

### Expected result

Site to work

### Actual result

Uncaught TypeError: window.TWILL.STORE.config is undefined

blank pages

### Versions

 2.7
 
8.3
 
7.3
 posgres

**Comment by ifox** [comment]
Hi @michaeljcoyne, it seems like you are encountering those errors because you are overriding Twill's main layout file. When you do that, you have to make sure to keep track of changes in Twill's sources after an update. The changes are usually minimal. Let us know if you need support identifying them. And make sure you published the Twill layouts view for a reason. If you are not changing anything in there, you should not maintain a copy in your project to avoid running into those issues.

**Comment by michaeljcoyne** [comment]
Hi @ifox I am not intentially overwritting it - how would I be doing this? Also it wasn't doing this before I upgrade to 8.1 beta then downgraded - so maybe this caused it.

**Comment by michaeljcoyne** [comment]
Also I dont understand why its not doing locally

**Comment by ifox** [comment]
Ok, reopening.

Are you sure you don't have a twill folder under views/vendor?

**Comment by michaeljcoyne** [comment]
Hi @ifox no I don't.

How I downgraded was to just delete the node_modules and vendor directory and rebuilt everything in production.

I tried switching branch on server but the issue persisted. I did a Twill update on the live server which cleared all the caches and seemed to revert back to 2.5. All a bit wierd.

**Comment by ifox** [comment]
Hmm, this doesn't seem related to Twill itself. As a first step I would recommend that you utilise composer lock file correctly so that you install the same version on your development and production environments. Then, regarding the assets build, if you are not using any custom components or blocks, you should not be building. `php artisan twill:update` will copy the build from the repo. However, the beta release doesn't include the latest build. I don't think you're saying this is affecting only the beta though, correct?

**Comment by michaeljcoyne** [comment]
I do have my composer lock under version control correctly. This is not my normal production process - I was just doing it to see if it got rid of the error - like something in the build script would fix it - which it did resolve the error, but also did something strange explained above. It may not be directly related to Twill or it maybe, not sure at this stage. Thanks

**Comment by michaeljcoyne** [comment]
Turns out my composer needed updating on the server. Thanks
