### ISSUE TITLE
hasImage() function throws exception instead of returning false

### ISSUE THREAD

**Issue by lindeVW** [area17/twill#1531]
## Description

Using the `->hasImage()` function on a model with the `HasMedias` trait will always throw an exception when the result should be `false`. Seems like this is caused by the `$this->findMedia($role, $crop);` that gets called, as in the `findMedia` function itself, the exception is thrown when the given crop is not found.

### Steps to reproduce

Call the `->hasImage` function on a model with the `HasMedias` trait.

### Expected result

Function returns `false`.

### Actual result

Throws a `MediaCropNotFoundException`

### Versions

Twill version:  2.7
Laravel version: 9.2
PHP version: 8.0.2

**Comment by haringsrob** [comment]
Hey @lindeVW,

This is a debug only exception. But I guess we can make it an optional one.

I added a pr.

**Comment by ifox** [comment]
Since this is causing a lot of confusion, and because I agree that `hasImage` should not be throwing an exception, even in debug, I would recommend we patch 2.7 by preserving the previous behavior of the `hasImage` function. In Twill 3, we can refactor to add a `cropExists` function as well as introduce the option as you already did. What do you think @haringsrob?
