### ISSUE TITLE
Blocks [Some questions]

### ISSUE THREAD

**Issue by Krato** [area17/twill#16]
Hello again. I have some blocks options:

I was able to create this three blocks;

```php
'blocks'   => [
            'title'     => [
                'title'     => 'Title',
                'icon'      => 'text',
                'component' => 'a17-block-title',
            ],
            'images'    => [
                'title'     => 'Image',
                'icon'      => 'image',
                'component' => 'a17-block-image',
            ],
            'contenido' => [
                'title'     => 'Content',
                'icon'      => 'text',
                'component' => 'a17-block-wysiwyg',
            ],
        ],
```

I create this views inside `resources\views`: 
<img width="325" alt="captura de pantalla 2018-07-16 a las 14 18 26" src="https://user-images.githubusercontent.com/74367/42758241-255f00b4-8903-11e8-9c52-27fbdb538876.png">

How I can render for example the title? What I should put in `blocks` and `title` views to show the title?

I just be able if I modify the BlocksController@preview method and override the last lines to:

```php
$view = view(config('twill.block_editor.block_single_layout'))->with('content', $renderedBlocks);

return html_entity_decode($view);
``` 

So in the title.blade I can see the preview using:
```blade
<div class="block__body">
    <h1>{{ $block->translatedinput('text') }}</h1>
</div>

```

Also, if I attach some image to the Image block, when I save, no mediable is set. So when reload there isn't image.

Thanks!

**Comment by ifox** [comment]
Hi @Krato!

What's the content of your `block.blade.php` layout?

As long as you yield a `content` section, you shouldn't have to override the `BlocksController@preview` method. 

```php
@yield('content')
```

As you can see below, Twill injects rendered blocks into the `content` section of your block layout.

https://github.com/area17/twill/blob/4d58468db4c2aec3bcbb7ed8c8de3dfb78c5240b/src/Http/Controllers/Admin/BlocksController.php#L60-L64

As for the image not saving in a block, it could be that you are missing crop parameters into your blocks config. See the default configuration:

https://github.com/area17/twill/blob/4d58468db4c2aec3bcbb7ed8c8de3dfb78c5240b/config/blocks.php#L17-L62

Are you trying to use the default provided image block or did you create you own? The default one has a medias field called `image`, which is why you can see above that the crops array has an `image` key with 3 crops defined. You can of course change it in your project by removing or adding crops and options. If your block uses a medias field with a different name, you would need to reference it there.

I see that apart from being shown in the configuration section of our docs, this isn't explained in the dedicated block editor section. Adding to my list of docs improvements to do!

**Comment by ifox** [comment]
Hey @Krato, I'm closing this as it looked like it wasn't a bug but more of a configuration issue. Feel free to follow up here or create another issue if you're still running into any trouble.
