### ISSUE TITLE
Error when using translated fields helper method in form requests

### ISSUE THREAD

**Issue by zeezo887** [area17/twill#1610]
## Description

Error when using translated fields helper method in form requests.

### Steps to reproduce

Add the `rulesForTranslatedFields()` helper method to either the `rulesForCreate()` or `rulesForUpdate()` method in a form request.

```
public function rulesForUpdate()
{
    return $this->rulesForTranslatedFields([], [
        'page_text' => 'required'
    ]);
}
```

### Expected result

It should define the rules for the specified fields.

### Actual result

An error is thrown.

```
BadRequestException
Input value "languages" contains a non-scalar value.
```

### Versions

2.x

**Comment by zeezo887** [comment]
@ifox I'm going to fix this.

**Comment by haringsrob** [comment]
Hey @zeezo887,

Could you share some more information on how to reproduce this?

Is it in a block/repeater or basic form?

Thank you

**Comment by domihagen** [comment]
Hey @haringsrob,
this issue is related to Laravel 9 that has a dependency to Symfony 6 where the breaking changes were made.
Someone already mentioned it in discord (https://discord.com/channels/811936425858695198/811986149064441927/966401384285110342). And sent this related Issue => https://github.com/symfony/symfony/issues/44432

Thanks @zeezo887 for fixing it!

Would be great to get this as a Hotfix.

**Comment by haringsrob** [comment]
Hey @domihagen @zeezo887 ,

Clear now, and reproduced. Will add to the next bugfix release
