### ISSUE TITLE
Editor Preview Scroll Jank

### ISSUE THREAD

**Issue by freshleafmedia** [area17/twill#1641]
## Description

The preview feature has terrible scroll jank. It is most noticeable in Firefox (almost unusable) but is there in Chrome too.

I believe it is caused by the [`PreviewerFrame` scroll event listener](https://github.com/area17/twill/blob/b32623b59c5bee4094f072419fed33067698cbe6/frontend/js/components/PreviewerFrame.vue#L49-L56). It causes all `PreviewerFrame`s to have their scroll positions updated which in turn then causes all `PreviewerFrame`s to have their scroll positions updated etc...

### Steps to reproduce

- Preview an editor
- Scroll the preview iFrame

### Expected result

Smooth scrolling

### Actual result

Scroll position jumps around and is janky.

### Versions

Twill version: 2.8.1
Laravel version: 9.11.0
PHP version: 8.1.5

**Comment by ifox** [comment]
Hi @freshleafmedia, it seems like you are talking about the compare feature of the previewer, not the block editor previews, correct?

On the preview itself I'm not experiencing scroll jank, but I do for sure on the compare, since it is trying to do synchronized scrolling on both which I'm honestly not sure can become very smooth, though we can certainly improve it. 

I'm confused by the fact that you're talking about the editor though, do you mean that you think this code might affect blocks previews?

**Comment by freshleafmedia** [comment]
Hi @ifox I don't think I was clear, it is limited to the whole page preview:

- Create a new page
- Click "Preview changes" in the sidebar
- Scroll the preview
- Optionally also select a revision to compare to

It's worth noting that using the scroll wheel is much worse than dragging the scroll bar.

**Comment by ifox** [comment]
@freshleafmedia could you share a video of what you are experiencing and a reproduction repository? It may be that what you are doing in the preview doesn't like being in an iframe or some other reason, but we're not experiencing this. Do you experience it on https://demo.twill.io too?

**Comment by freshleafmedia** [comment]
@ifox The demo works exactly as expected. It was, as you said, something in our preview. Specifically we were setting `scroll-behavior: smooth;` on the body element in the preview.

Thanks for the help
