### ISSUE TITLE
Inactive slug trigger suffix slug

### ISSUE THREAD

**Issue by thingasd** [area17/twill#1755]
## Description

Inactive slug trigger suffixSlugIfExisting, only page is trashed / destroyed the slug will be available again.

### Steps to reproduce

https://user-images.githubusercontent.com/29519267/180394795-e6c9a6f8-d2c2-45c4-b591-4280721e442f.mp4

### Versions

Twill version:  2.8.8

**Comment by haringsrob** [comment]
Hey @ifox, shouldnt the slug update instead of creating a new entry?

This is the db after entry create + update.

<img width="794" alt="Screenshot 2022-08-16 at 14 46 49" src="https://user-images.githubusercontent.com/866743/184883151-735bf720-fec1-447b-8faa-ebbf679212fa.png">

Asking because there might be a reason for it.

**Comment by ifox** [comment]
It was a voluntary decision in Twill 2 to prevent reusing slugs of soft deleted models because one could restore these in the UI. It would be a breaking change to release this in Twill 2, so I'm going to close this and the associated PR, since this has been changed in Twill 3.
