### ISSUE TITLE
No formfield value for fields based on conditional logic

### ISSUE THREAD

**Issue by daankloek** [area17/twill#186]
Hi,

We are making our first project on Twill, so far really awesome!

When I have a form field that is shown based on a specific selection of an other form field it does not load the saved value.

```
@formField('select',[
        'name'=>'type',
        'options'=>$typeOptions,
        'label'=>'Banner page',
        'default'=>'home'
    ])
    @component('twill::partials.form.utils._connected_fields', [
            'fieldName'=>'type',
            'fieldValues'=>'category'
        ])
    @formField('select',[
        'name'=>'instance_id',
        'options'=>$instanceOptions,
        'label' => 'Categorie',
        'default'=>collect($instanceOptions)->first()['value']
    ])
    @endcomponent
    @component('twill::partials.form.utils._connected_fields', [
            'fieldName'=>'type',
            'fieldValues'=>'home'
        ])
        @formField('select',[
        'name'=>'home_position',
        'options'=>$homeOptions,
        'label' => 'Positie'
        ])
    @endcomponent
```

So based on the selection of `type` it can display a select field `instance_id` OR a select field `home_position`.

When it gets saved it's all stored nicely, but when you open the form to edit it, it does not show the form field value of `home_position`. When selected type = `category` the form field value of `instance_id` is displayed correctly...

**Comment by ifox** [comment]
It looks like your issue is due to the select field not being rendered with the correct type that you previously selected, which is hiding your home_position field. Let us know if you still run into this, but hopefully our upcoming updates to the documentation which include implementation details for each form field and compatibility with its context (form, block, repeater, repeater in a block, settings) will help.
