### ISSUE TITLE
[3.x] New docs QA

### ISSUE THREAD

**Issue by ifox** [area17/twill#1994]
cc @kylegoines @haringsrob 

- [x] Missing style for lists within content (`<ul>`/`<ol>`), example in below screenshot:
<img width="786" alt="Screenshot 2022-12-12 at 4 01 28 PM" src="https://user-images.githubusercontent.com/708498/207078766-48086496-5157-43ed-a386-291f9458dfab.png">

- [x]  Footer should be removed and let's prevent whitespace at the end of the page (see behavior on current docs)
<img width="1449" alt="Screenshot 2022-12-12 at 3 54 34 PM" src="https://user-images.githubusercontent.com/708498/207076989-2f12babd-c34a-454f-96a8-229ac6708737.png">

- [x] Missing sticky header (see behavior on current docs)
- [x] Missing sidebar child items active state
- [x] Missing previous/next links
- [x] Missing edit this page on Github links
- [x] Incorrect order of child items in some sections (eg. Block editor)
- [x] Table of content should be right aligned on large enough screens

**Comment by kylegoines** [comment]
@ifox  happy to make  these changes, i had discussed with @haringsrob some of the issues, with the current template and layout. Some changes to the build might have to be made to archive design parity vs the figma. For clarification, i should use the current twill docs as a source of truth rather than the figma?

 Missing sticky header (see behavior on current docs)
      - i can make this update
 Missing sidebar child items active state
      - i talked to @haringsrob  about this he said he could add that to the build process
 Missing previous/next links
      - @haringsrob  is this something i need from the build process?
 Missing edit this page on Github links
      - i believe i can add this with a new block
 Incorrect order of child items in some sections (eg. Block editor)
       - @haringsrob is this a build issue
 Table of content should be right aligned on large enough screens 
       - i believe you mean the index.html page @haringsrob mentioned theres no way to swtich templates in the current build
       if theres a way to add a top level page class in the build we can probably remove it with css

**Comment by ifox** [comment]
Hey @kylegoines yes @haringsrob will help with the changes in templates and features I'm requesting. Responding shortly about your questions.
