### ISSUE TITLE
Any plans to support localization?

### ISSUE THREAD

**Issue by julihermes** [area17/twill#202]
I looked in the documentation and found nothing about location, any plan to support it?

**Comment by ifox** [comment]
Hi @julihermes!

Do you mean providing a way to translate Twill's admin console itself, through Laravel's translations files?

**Comment by tomascardenal** [comment]
@ifox hi! Talked to you on Spectrum about this same issue, and talked about this being in your roadmap. If done atm, would you be more inclined to having calls to __() or trans_choice() and providing a default lang/en.php, or having variables so that someone can override them, and, if they choose to, use Laravel's internacionalization like on pull request #228 ? We'd love to help implement this feature if possible, too. 

Thanks in advance for your time.

**Comment by yanhao-li** [comment]
The relating PR is here: https://github.com/area17/twill/pull/405
Closing this issue for now.
