### ISSUE TITLE
[2.x] BC BREAK: Str::afterLast is not compatible with old Laravel versions

### ISSUE THREAD

**Issue by antonioribeiro** [area17/twill#2029]
## Description

Twill versions superior to 2.12.0 [introduced Str::afterLast](https://github.com/area17/twill/commit/c0bf9aa884e5c70a846ce2a96b5d4a4b1ad7d774#diff-8a3084d617335690e3d80eadc43ada1afa56002be98b5b69ca778ead9a4849ecL464) which doesn't exists on Laravel 5.8, I believe we need to move to use Twill's own `str_after_last()` for now.

**Comment by haringsrob** [comment]
Hey @antonioribeiro 

Normally we do not really support unsupported laravel versions. But since this is a small change I'll take care of it.

https://laravel.com/docs/9.x/releases#support-policy

**Comment by antonioribeiro** [comment]
I didn't know about this, @haringsrob , thanks for letting me know, but now I also have a question: why are we doing [this kind of change](https://github.com/area17/twill/commit/059caa67c149bceb01918492d1bb3fa122387b0c#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34L34) (removing support for old Laravel versions) on a patch?

Removing support for old framework versions is a change that should be done on major versions only. You can stop where you are (saying _"sorry, we are not working on Twill 2.x anymore"_) and just work on 3.0, but keep advancing 2.x and at the same time remove support for old Laravel versions will harm projects using Twill or, at least, make things awkward.

And if you do (yeah, you can do whatever you want), you need to come forward and say very clearly: _"we are not supporting Laravel 7 and lower anymore on Twill 2.x, last supported version is Twill 2.12.0"_. Not sure if you did...

/cc @ifox

**Comment by ifox** [comment]
Dropping unsupported Laravel versions has always been planned for Twill 3, not Twill 2, where we have no reason to drop support since we've previously spent the effort to maintain it, and as we're following semver, Twill 2 should indeed not have introduced incompatible Laravel code or dropped support for installation with Laravel versions it previously supported.

The composer.json changes were released as part of https://github.com/area17/twill/pull/1923 with 2.12.1 and omitted from the changelog because it was an unrelated hotfix release. 

@haringsrob I understand that we could want to stop running CI tests for unsupported Laravel versions, but we can't prevent the installation of Twill on those versions that were supported by 2.x. Or, as @antonioribeiro suggested, we would have to have a table of supported versions documenting that Twill > 2.12.1 is Laravel 8+ only. Which, I don't want to end up with, as we would then struggle to release security fixes on 2.x that would benefit all supported versions.

Can we please revert those requirements changes and make a new 2.x release?

**Comment by haringsrob** [comment]
This was restored in https://github.com/area17/twill/pull/2032, my apologies for the inconvenience. 

I did not discuss this properly on my end which led to a miscommunication.
