### ISSUE TITLE
[3.x] Improve Form builder workflow

### ISSUE THREAD

**Issue by aksiome** [area17/twill#2141]
## Summary

I really love the new Form building workflow but I found it to be a bit verbose. So I'd like to propose an alternative syntax. The main goal is to reduce the number of imports and method calls. If you think it's a good idea, i can work on a PR.

## How it works
The main idea is to use the Form service class as a global factory for all fields. The method will have for arguments the mandatory properties without the label. An other improvement is to allow the options method to also accept an array.

Additional syntax:
```php

use A17\Twill\Services\Forms\Form;

return Form::make([
    Form::tags('tags'),
    Form::input('name')->label('Foo'),
    Form::select('select', [
        'foo' => 'bar',
    ])
]);
```

Current syntax:
```php

use A17\Twill\Services\Forms\Fields\Input;
use A17\Twill\Services\Forms\Fields\Select;
use A17\Twill\Services\Forms\Fields\Tags;
use A17\Twill\Services\Forms\Form;
use A17\Twill\Services\Forms\Option;
use A17\Twill\Services\Forms\Options;

return Form::make([
    Tags::make()->name('tags'),
    Input::make()->name('name')->label('Foo'),
    Select::make()->name('select')->options(Options::make([
        Option::make('foo', 'bar'),
    ]))
]);
```

This should not add too much complexity to the codebase. The idea is to use  __callStatic and proxy object creation to the already existing classes.

**Comment by haringsrob** [comment]
Hey @aksiome!

Thank you for reporting. However, I personally am not a big fan of this. Not because it does not look good, but simply because php does not allow us to do this properly.

When we use static, or even would create a setter for every type, that would add a lot of maintenance on top of what we have.
In addition to that (depending on the approach) your editor/lsp would not know what `Form::tags` actually returns (unless we specifically go and document it/make a typed initialiser).

On top of that, this would make it more difficult for external packages to contribute fields. What you can do now is create an extension of any of the fields we provide, make it your own and then use it in the form.

Lastly to touch on the Options::make and Option::make, I agree it looks too verbose. But it solves a specific problem of what structure of array does my field want?

There are/were many ways to do this before:
```php
[
  'bar' => 'foo'
]
```

```php
[
  [
    'value' => 'bar',
    'label' => 'foo',
]
```
...

By the new approach there is just one way to do it, the objects and what you can insert into them are enforced so there is no more room for error.

This does not mean we could add a helper like `Options::fromArray([...])`!

I hope this explains a bit the intend of the current approach.

I will leave the issue open for a bit to maybe hear other opinions as well.

Cheers!

**Comment by aksiome** [comment]
Hey @haringsrob thanks for the answer,

I get why this could bother you. Concerning IDE and autocompletion, I was planning to use phpdoc like laravel is doing with its Route facade because it adds almost no complexity.

*On a side note I noticed that the current Facades (mainly TwillRoutes and TwillNavigation) suffer from the same issue. I think it would be nice to add some phpdoc for them.*

Before given up on this I still want to propose an other approche, it's more code but I can see some benefits.

Use a TwillForm class at the root and a Facade for it. This class will have twill form classes pre registered and the Facade will have phpdoc to help with these. The advantage here is to allow users to register any kind of type during the boot phase. This way you can register a complex reusable form structure and use it multiple times across the whole app. Not really sure how the register function could look like, but I'm sure i can come up with something nice using either namespace registration (if I remember correctly Respect Validation does something a bit similar to this), individual class registration, or closure to compose reusable structures. It does not really change the fact that phpdoc is needed to help the IDE, but it's a bit more flexible when it comes to external fields.

Concerning the option my idea was to convert key => value to an Option with the key as the name and value as the label. The selectable param would just be set to default. If someone wants to use it, they can still use the Option class like this:
```php
[
	'value' => 'label',
	Option::make('value', 'label', false),
];
```

Quick implementation exemple:
```php
// HasOptions trait
public function options(Options|array $options): static
{
	$this->options = is_array($options) ? Options::make($options) : $options;
	return $this;
}

// Options collection class
public static function make(array $options): static
{
	parent::make(collect($options)->map(
		fn ($label, $value) => $value instanceof Option ? $value : Option::make($value, $label)
	));
}
```

Thanks for reading me and working on this great package. I really love the experience so far!

**Comment by haringsrob** [comment]
Hey @aksiome,

I still do not see a real benefit to making this more abstract. I feel in the long run it will not help us and increases maintenance on the code.

What we are open for is a helper for example for options:

```php
Options::fromArray(['bar' => 'foo', ...])
```

Feel free to open a pr :).

Cheers,
