### ISSUE TITLE
Use Tiptap WYSIWYG Editor instead of Quill

### ISSUE THREAD

**Issue by octoper** [area17/twill#215]
You should use Tiptap WYSIWYG Editor instead of Quill, it's more extensible and it's working better with Vue.js.

Tiptap Werbsite: [https://tiptap.scrumpy.io/](https://tiptap.scrumpy.io/)

**Comment by ifox** [comment]
Hi @octoper,

thanks for the suggestion. Quill has been working great for us, but I know Tiptap is a very interesting alternative. In Twill 1.2.2 we improved our Quill powered form field, but we are still looking for more improvements, so will definitely keep Tiptap in mind.

**Comment by arkid** [comment]
Desperately hoping that Quill 2 is released sometime soon as the lack of table support is really a problem for me. I had an embarrassing incident where I just assumed that some basic copy/paste table support would work in Twill so told a client the same...  yet it doesn't work due to a total lack of table support in Quill :(

Pasting from things like MS Word/Excel are a working world reality for many users of a CMS.
