### ISSUE TITLE
yanhaoli/create-twill-app 1.0.8 requires php ^7.2.9 -> your php version (8.0.14) does not satisfy that requirement.

### ISSUE THREAD

**Issue by michaeljcoyne** [area17/twill#2168]
## Description

I am trying to install a global npm package. (Expose)

### Steps to reproduce

composer global require beyondcode/expose

### Expected result

For this to not produce errror.

### Actual result

  Problem 1
    - yanhaoli/create-twill-app is locked to version 1.0.8 and an update of this package was not requested.
    - yanhaoli/create-twill-app 1.0.8 requires php ^7.2.9 -> your php version (8.0.14) does not satisfy that requirement.

### Versions

 Version 2.12.4

8

**Comment by mattdinthehouse** [comment]
Even though you're installing `beyondcode/expose` the issue is coming from the `yanhaoli/create-twill-app` package in your composer.json

`yanhaoli/create-twill-app` isn't a first-party Twill library so you should file an issue report there - https://github.com/yanhao-li/create-twill-app - but I can see there's been no new commits on it since 2020 so it's probably better for you to remove that package entirely

**Comment by michaeljcoyne** [comment]
Hi @mattdinthehouse 

I did take a look at that repo and figured the same as you. I thought package must be included in the Twill installation as I do not recall installing it. So thought I would mention it here.

I can see @ifox has forked it.

Maybe it was a previous dependency. Not sure.

Thanks

**Comment by mattdinthehouse** [comment]
Doesn't look like there's any dependants on it https://packagist.org/packages/yanhaoli/create-twill-app but either way it's an abandoned project (even ifox's hasn't been touched since 2019) so you're probably good to uninstall it

**Comment by haringsrob** [comment]
hey @michaeljcoyne, unfortunately we cannot really provide support for external packages.

They create-twill-app is having a dependency on php 7.2, best would be to post the issue there.
