### ISSUE TITLE
Twill Media Library generating incorrect image url when using Glide with AWS S3

### ISSUE THREAD

**Issue by theia-kevin** [area17/twill#2236]
## Description

Incorrect image url generated when using Glide with AWS S3

### Steps to reproduce

Config .env file as below
```
MEDIA_LIBRARY_ENDPOINT_TYPE=s3
MEDIA_LIBRARY_CASCADE_DELETE=true
MEDIA_LIBRARY_LOCAL_PATH=uploads
MEDIA_LIBRARY_IMAGE_SERVICE=A17\Twill\Services\MediaLibrary\Glide
S3_KEY=foobar
S3_SECRET=foobar
S3_BUCKET=foobar
```

### Expected result

Below is a working url generated when using `A17\Twill\Services\MediaLibrary\Local` 
`https://infomate.s3.ap-southeast-2.amazonaws.com/6dde5274-a0af-482d-a367-6207ce2ebe6d/500x500.png` 

### Actual result

When using S3, shouldn't the url be pointing to S3 endpoint?
`https://infomate.test/img/6692f470-b9f5-425c-9df6-be124f142118/500x500.png`

https://flareapp.io/share/OmVpJ437#F40

### Versions

`"area17/twill": "haringsrob-patch-1-dev"`

` "laravel/framework": "^10.0",`

`PHP 8.2.5 (cli)`

`mysql  Ver 8.0.32`

**Comment by ifox** [comment]
Hi @theia-kevin, no, it should not generate a S3 url, because Glide is a dynamic image rendering service. With Glide, image requests need to go through your Laravel application for the parameters to be processed. From there it can return the cached image transformation. 

If the URL generated was pointing to S3, adding parameters, e.g. w=1000, would have absolutely no effect. 

Because of the nature of Glide, Glide + S3 is not optimal without using a CDN on top of the Glide /img route, because there's too much overhead in having your Laravel application return an S3 file, even when Glide already generated a cached image. 

However, you can decide to use S3 as your Glide source while using local as your Glide cache, which is more performant but requires space on your server.

Ultimately, this is why Twill also offers dedicated image rendering services compatibility, like Imgix and Twicpics.

Finally, if you get an error on the generated Glide image URLs, check your logs, you might be missing the GD or Imagick PHP extensions.

**Comment by ifox** [comment]
The error you shared is actually saying that your Laravel application isn't able to write to the log file, so you'll need to fix that before seeing the actual error.

**Comment by theia-kevin** [comment]
> Hi @theia-kevin, no, it should not generate a S3 url, because Glide is a dynamic image rendering service. With Glide, image requests need to go through your Laravel application for the parameters to be processed. From there it can return the cached image transformation.
> 
> If the URL generated was pointing to S3, adding parameters, e.g. w=1000, would have absolutely no effect.
> 
> Because of the nature of Glide, Glide + S3 is not optimal without using a CDN on top of the Glide /img route, because there's too much overhead in having your Laravel application return an S3 file, even when Glide already generated a cached image.
> 
> However, you can decide to use S3 as your Glide source while using local as your Glide cache, which is more performant but requires space on your server.
> 
> Ultimately, this is why Twill also offers dedicated image rendering services compatibility, like Imgix and Twicpics.
> 
> Finally, if you get an error on the generated Glide image URLs, check your logs, you might be missing the GD or Imagick PHP extensions.

@ifox Thankyou so much, what you explained make sense.
