### ISSUE TITLE
FormBuilder Browser field with single module

### ISSUE THREAD

**Issue by iedex** [area17/twill#2424]
Can this be true?
https://github.com/area17/twill/blob/063b4bbbe2b133f48008de250be8f767ce2350c1/src/Services/Forms/Fields/Browser.php#L148

What will be the best change?

**Comment by ifox** [comment]
Yes it can, in the case where $modules is an array that contains exactly one element, but that element is not at the index 0. This can happen if the array uses non-sequential or non-numeric keys.

Non-sequential keys: If the array's keys are not sequential, and the starting key is not 0, then count($modules) could return 1 (indicating that there is one element in the array), but $modules[0] would not be set because the key 0 does not exist in the array.

Associative array with a single element: If $modules is an associative array (where keys are strings instead of integers), and it contains just one element with a key other than 0, count($modules) would be 1, but isset($modules[0]) would evaluate to false since there's no element with the key 0.

This condition is to account for someone passing something like this: `['posts' => Post::class]`.

**Comment by iedex** [comment]
Ah, got it. I was looking for a method to use only one module, because moduleName doesn't work in FormBuilder, and when using modules(['module_name']) the browser has that selector for the single module.
Tried now and it works as expected with ->modules(['name' => 'module_name']).
Thanks a lot!
