### ISSUE TITLE
Override navigation._title partial

### ISSUE THREAD

**Issue by tchapi** [area17/twill#247]
Hi,

I would like that the upper left navigation title (_name of the site + `prod` or `local`_) redirect to the admin panel (`/admin` in my case) and not the root folder (`/`) as it is the case right now.

I don't think there is a configuration for that (AFAIK it's hardcoded here : https://github.com/area17/twill/blob/1.2/views/partials/navigation/_title.blade.php) but maybe I can override this small partial template easily ?

Thanks  a lot for your help !
BR

**Comment by ifox** [comment]
Hi @tchapi,

You are right, it should automatically support using a path for the admin homepage instead of just defaulting to the root path which only works for users of the admin subdomain. I'll add to our next release. In the meantime, you can override the partial under `resources/views/vendor/twill/partials/navigation/_title.blade.php` in your own app. This is true for any Twill view but we do not recommend publishing them all as it can make future maintenance more complex.

**Comment by tchapi** [comment]
Alright, the override works great but you're right about the maintenance overhead
Thanks a lot

**Comment by ifox** [comment]
This should now be working correctly in 1.2.2 thanks to this update 28d8fcd599883957c84dda94d67213d6a00253a7.
