### ISSUE TITLE
Edge: Editor mode display blank blocks

### ISSUE THREAD

**Issue by luislavena** [area17/twill#274]
Tested a Work in Demo (https://demo.twill.io/work/works/2335/edit) and no preview of the block elements is displayed, only blank boxes.

No errors are displayed in the console and all the associated functionality works, except for the preview of each block.

* OS: Windows 10
* Browser: Microsoft Edge 
* Browser version: 18.17763
* Screen resolution (as reported by Edge): 1435 x 688
* Real screen resolution (HiDPI, 225%): 3200 x 1800

See attached screenshots:

![ApplicationFrameHost_ktPMyY34rh](https://user-images.githubusercontent.com/4182/58043710-404f1e00-7b14-11e9-937b-b5049223bef4.png)
![ApplicationFrameHost_pNnl3BVvSG](https://user-images.githubusercontent.com/4182/58043718-4644ff00-7b14-11e9-90ad-61d413e60e83.png)

Thank you!
❤️ ❤️ ❤️

**Comment by mrdoinel** [comment]
The blank blocks in Editor and Preview must be related to srcdoc not supported on Edge : https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/12375527/

Because Edge browser does not support the HTML <iframe> srcdoc attribute. It will arrive with Edge 75 (the chromium based version of Edge)
https://caniuse.com/#feat=iframe-srcdoc

**Comment by ibjorn** [comment]
I get the exact same thing with Chrome. I thought it might be related to the npm twill-build script which fails when building.

**Comment by ifox** [comment]
See #275.
