### ISSUE TITLE
How to add custom JavaScript that responds to form events?

### ISSUE THREAD

**Issue by nikhiltri** [area17/twill#28]
Hey all,

Thanks for the great package! We're working on customizing our CMS, and we'd like to add Javascript that responds to an event—like when a user clicks on an option in a browser or removes a selected browser option. I understand we can use `@push` to add our own JS, but how do we reference/listen to form change and click events?

Thanks for all your work!
nikhil

**Comment by ifox** [comment]
Hi @nikhiltri!

Thank you so much for your kind words :)

The first way that come to my mind would be to listen to events manually by attaching to the form DOM directly in your custom Javascript. However, you might struggle to find the right selector to do that! Maybe adding an option to add a custom identifier to all Twill's form fields would be a good idea to help with that, even though you could most likely already target the right thing without that. 

In the example of the browser field, you can listen to changes on the value of the hidden input its markup contains. However this wouldn't allow you to hook in your code before the actual action happen in the component. 

You could also attach a click event to the remove icon for example, but I'm not sure of the order of execution there. I just read [this](https://stackoverflow.com/questions/16273635/how-do-multiple-addeventlistener-work-in-javascript) and it seems like it is executed in the order of registration on browsers that correctly implement DOM 3.

It seems like what you actually need are `before` and `after` hooks on Twill existing events, right?

In speaking with @m4n1ok, the idea of providing extensibility through Vue plugins came up, but I'm not sure yet how it would help in this specific case.

**Comment by nikhiltri** [comment]
And yes, adding the ability to add a custom ID would be helpful. Unless you can suggest how to identify a specific multiselector/browser where there are a few multiselectors and browsers on a form?

**Comment by ifox** [comment]
This implementation looks good to me, yes.

However, you will need to need to wait for Vue to render the element you want to target before being able to attach an event listener. Right now you could probably do that by listening to mutations on the main Vue `app` div:

https://github.com/area17/twill/blob/4d58468db4c2aec3bcbb7ed8c8de3dfb78c5240b/views/layouts/main.blade.php#L48

The `v-cloack` attribute is removed by Vue once its instance finishes compilation, see [Vue API docs](https://vuejs.org/v2/api/#v-cloak).

However we are thinking about sending a global event, for you to listen to, from Twill's Vue apps `mounted()` hook, something like `vue-mounted`.

On the broader subject of extensibility of our Vue components, I had the chance to touch base with @m4n1ok and here's what we are thinking:
- similar to  how Laravel packages' views overriding works, we could accept a folder of Vue components in host applications that would replace Twill's provided components
- this would allow you to completely change any behaviors and styling of all components
- but this might become a maintainability burden, so you could also decide to[ extend our components using the `extends` Vue components' option](https://vuejsdevelopers.com/2017/06/11/vue-js-extending-components/).

Does that sound like a good option to you? We feel like apps using Twill would definitely benefit from using Vue.js to customize their CMS too, instead of having to manually fiddle with a DOM that is not necessarily intended to be dealt with outside of Vue apps.

**Comment by ifox** [comment]
In the meantime, here's how you could identify a multiselector/browser for example the "Add" button when there are a few multiselectors and browsers on a form:

something like `document.querySelector("label[for='browsers.homeFeatures'] + div .browserField__trigger button")` should work.

![screen shot 2018-08-10 at 2 26 36 pm](https://user-images.githubusercontent.com/708498/43977508-65ed52d0-9cb2-11e8-9cb3-a8f4c382f230.png)

**Comment by yanhao-li** [comment]
A quick note that in the pull request https://github.com/area17/twill/pull/218
I did a little tweaks in the `layout/form.blade.php`, which could allow us to to listen the store state change in the `extra_js` stack.
```php
@push('extra_js')
    <script>
        window.vm.$store.subscribe((mutation, state) => {
            if (mutation.type === 'updateFormField' && mutation.payload.name === 'attributes') {
                 // do something
            }
        });
    </script>
@endpush
```

**Comment by devimako** [comment]
i need to use onchange function in the formfields to get value from the form is it possible
<img width="985" alt="Screenshot 2023-02-13 at 6 39 23 PM" src="https://user-images.githubusercontent.com/99637767/218466991-663af273-3f4e-434a-a773-5a2bf82121ac.png">
