### ISSUE TITLE
Preview link gives 405 response

### ISSUE THREAD

**Issue by LCD344** [area17/twill#317]
I just started playing around with twill, to see how quickly I can get a page set up, and immidietly I hit a snag in where I couldn't get the preview to work, I followed the guide to set up a Page module, added backend navigation and some form fields but then when I click the preview button I get an error message - looking at the developer tools and comparing with the route list and the demo project, it doesn't seem to be hitting the right endponts

![image](https://user-images.githubusercontent.com/15718141/60771213-292cb580-a0ed-11e9-92fa-f8ea866d3bc9.png)

I already added a resources/site/page.blade.php, and all the other steps that the guide mentions in the CRUD modules part. what am I missing?

Thanks

**Comment by yanhao-li** [comment]
Hello @LCD344 ,

From what I can find, the permalink on your screenshot is really sketchy:
![image](https://user-images.githubusercontent.com/12378652/60896055-a9f5c980-a233-11e9-819c-1a5a0266b3db.png)

It's very likely that when you create your pages module, you have capitalized your module name, i.e
you were using `php artisan twill:module *Pages*` instead of `php artisan twill:module pages`. Read our documentation [here](https://twill.io/docs/#cli-generator)

Twill's module generator currently is not smart enough to recognize it, and we are planning to improve this in the future, stay tuned!

For now, I would recommend regenerate the module using the correct name format, otherwise you could also rename them manually.

**Comment by LCD344** [comment]
Yes, that was indeed the issue, I did think it was weird that y'all wrote it with lower case (Thinking that class names start with capital) and since the documentation didn't state anything like that explicitly I thought it was a typo lol.

Resolved
