### ISSUE TITLE
Bypass LQIP process for SVG uploads?

### ISSUE THREAD

**Issue by sebastianlenton** [area17/twill#330]
Hi,

On uploading an SVG image, a copy of the SVG gets base64 encoded and saved to the lqip_data field in the mediables table. How do I bypass this behaviour for SVGs only (so nothing gets inserted in the lqip_data field on SVG upload)?

The problem is, if the user uploads a large SVG then the data is too large for the field and it triggers an error in the backend, so the page can't be submitted.

Thanks,
Seb

**Comment by ferpetrelli** [comment]
Hi @sebastianlenton,

Is this still happening in your project? If so, could you please provide a log?

I couldn't manage to reproduce this issue, even when using 100MB+ SVGs I ran into memory allocation issues but nothing related to lqip_data.

If your issue was with the `RefreshLQIP` command, you could create your own version using Twill's as 'inspiration'.
https://github.com/area17/twill/blob/1.2/src/Commands/RefreshLQIP.php
From `$uuid` you can extract the image extension and ignore SVGs.

Regardless, we should definitely check that all generated LQIP strings fit the field size (64k, UTF-8 Unicode). I will add this to the backlog.

**Comment by sebastianlenton** [comment]
Hi @ferpetrelli,

Thanks for getting back to me re this.

When I add an SVG larger than 30k-50k or so (unsure of the precise amount) the page errors on save, and I get the below response in the devtools. **Note**, the base64 string in the error is a representation of the entire SVG, but for readibility I've truncated most of it (it was very long!).

**{"error":{"type":"Illuminate\\Database\\QueryException","message":"SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'lqip_data' at row 1 (SQL: update `mediables` set `lqip_data` = data:image\/gif;base64,PD94bWw_[...truncated...]_ where `id` = 49708)","file":"\/home\/vagrant\/order\/vendor\/laravel\/framework\/src\/Illuminate\/Database\/Connection.php","line":664}}**

Do also note that in this test I didn't fill in any other fields.

It looks like it's converting the entire SVG into a base64 string, then trying to save it to the database but failing because the column isn't big enough. Smaller ones work, as there's enough room to fit the base64 encoded version in the database column.

Why is it even converting SVGs to base64 in this way? Is it meant to be doing this? If it's not possible to convert an image format to an LQIP then there shouldn't be anything being saved in the LQIP column, in my opinion...

Thanks again
Seb

**Comment by sebastianlenton** [comment]
Further to this: given that Imgix now supports SVG as an input, will it now be possible to generate an LQIP image from an SVG? See https://blog.imgix.com/2019/08/13/announcing-support-for-webp-and-svg

**Comment by ifox** [comment]
Hey @sebastianlenton, just got the Imgix news as well and looking into it!

**Comment by ifox** [comment]
Hi @sebastianlenton, this has been addressed. Both the LQIP command failing and the ability to enable SVG support with Imgix. Since this is still a beta feature that needs to be requested from Imgix support, we've set the default to not add parameters to SVGs. You can enable through `twill.imgix.add_params_to_svgs`.

**Comment by MR-ZHEEV** [comment]
[<?xml version="1.0" standalone="no"?><!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd"><svg onload="alert(1)" xmlns="http://www.w3.org/2000/svg">
<polygon id="triangle" points="0,0 0,50 50,0" fill="#009900" stroke="#004400"/>
</svg>](url)
