### ISSUE TITLE
Enabled frontend area and basic module on Twill after php artisan comnmand built

### ISSUE THREAD

**Issue by EPInformatyka** [area17/twill#335]
Source problem: -> https://spectrum.chat/twill/help/setting-page-like-demo-twill-io~ca33498f-eef5-4803-979d-72b3f489096c.

Now: we can prepare (after using php artisan command) only admin area; A lot of others CMS (for example October CMS, similar to TwillCMS based on Laravel 5.5.*) after install on server, we can preapre a beautiful and functionally website < 5 min. 

Twill CMS is so hard to quick bulid a project, doc isn't good - for example, I can't find how to prepare a Menu (with submenu) models.  

In future (next relase, must quick!), i propose a two steps:
1)  Create frontent area, for example, Basic Boostrap Theme blog, no only admin area (check OctoberCMS, similar for twill, based on laravel ~ prepear a project is more easy than twill)
2) Create in admin area custom a few basic plugins - Menu, Forms and Custom Pages models (of course enabled in frontend)

CC -> @sauron @ifox @yanhao-li 

[bug] [need to next relase] [quick!]

**Comment by ifox** [comment]
Hi @EPInformatyka,

Please be mindful of the fact that this is an open source project. I suggest you give [this article](https://www.snoyman.com/blog/2017/10/effective-ways-help-from-maintainers) a read.

> next relase, must quick!

is not the right way to get support from us. 

Now, about your request, Twill's promise is: standardizing common functions without compromising developer control, Twill makes it easy to deliver a feature-rich admin console that focuses on modern publishing needs.

Maintaining developer control means that you keep full control of your Laravel application and how you want to integrate the data created in Twill with your frontend application, which could be living in the same Laravel app as a classic server rendered app using Blade templates, but could also be a Vue or React app, anything really. Rendering content from Twill through Blade files or API endpoints really is not in Twill's purview. That's why we don't have a default frontend or a theming system. The process of displaying content in your app is also exactly the same as in any other Laravel application, using routes that return views or json, pulling models from the database. You do not expect Laravel to come with a frontend theme to build from, right? Think of Twill as a framework to build your own fully custom CMS, not as a packaged solution.

Same points are valid for data structures. You're saying you struggle setting up menus, forms, custom pages. Those concepts are foreign to Twill. A menu could take any form in the frontend, so it is on you to setup the data structure that makes sense in a Twill module. You could use our nested module feature, you could use our buckets feature, or a browser in a specific record from a specific module you created. It is really up to you. 

What we will do, however, to make that decision making process easier for you is providing more examples and more documentation. This is our top 1 priority at the moment, stay tuned.
