### ISSUE TITLE
Preview-Link misses a colon / Preview shows 404

### ISSUE THREAD

**Issue by renepardon** [area17/twill#344]
Hello,

I try this nice little framework right now and found an issues with the preview link. I've created a first module with "everything" just to see what a CRUD module can look like. I've called it **test**. So far so good. But when adding a title for multiple languages and then clicking on the preview link, I see that the colon is missing within the URI: `http//localhost:8000/.....`. If I add this colon manually I just see a 404 page. I've created a `views/site/test.blade.php` but this is only displayed within the frame preview, not when opening the published content.

See on the bottom when I hover the link:

<img width="331" alt="Screenshot 2019-08-07 08 04 39" src="https://user-images.githubusercontent.com/945323/62598776-b892d780-b8ea-11e9-8b91-8bc4cfba08c7.png">

**Comment by renepardon** [comment]
Really? Closing this issue without a comment automatically resolves it? ;)

**Comment by ifox** [comment]
We're doing some cleanup and migrating relevant discussions to GitHub Discussions. Seeing how far back this issue was from and knowing this has been fixed since then, I decided to close and didn't take the time to link back to the fix, yes, sorry about that. There's nothing wrong with asking to reopen if you still run into the issue though.
