### ISSUE TITLE
Deleting medias from file storage

### ISSUE THREAD

**Issue by nikhiltri** [area17/twill#37]
Hey Twillers (Twillistas? Twillamis?),

We're noticing that when a Media gets deleted from Twill, the file never gets deleted from file storage, even when there's no data in the database pointing to that resource. There are two scenarios we're thinking about:

- Soft deletes: If a `medias` and related `mediables` records get soft deleted, it would make sense for the file to stay in storage, since the pointer in the database still exists.
- Force deletes: If a `medias` gets `forceDelete()`ed, I think it would make sense for the file to be deleted from storage as well.

One way to do this might be having the `A17\Twill\Models\Media` model override the `forceDelete()` method to make a called to `Storage::delete` to remove the resource from storage after a successful request to the method. But taking a step back, is this behavior that should already be managed by Laravel's File Storage system? Or is this indeed behavior Twill would need to implement?

Thanks!
nikhil

**Comment by ifox** [comment]
Hey @nikhiltri!

Twillamis  😄😆😄

Twill actually has a configuration and environment variable for that: `twill.media_library.cascade_delete` and `MEDIA_LIBRARY_CASCADE_DELETE`. Same thing for the file library: `twill.file_library.cascade_delete` and `FILE_LIBRARY_CASCADE_DELETE`.

Right now, you can see it in the docs [here](https://twill.io/docs/#installation), in the example `.env` file. But stayed tuned, we're finally ready to release Twill 1.2 this week, which includes a completely revamped documentation, especially around configuration.

The idea right now is that admin users can only soft delete references from the UI, but you can use that option if you would like actual files to be physically deleted from storage when that happens. Since the UI prevents deleting a media or file that is currently being attached to a module or block, there are no risks in deleting files from storage as well. But taking a step back too, I'm now wondering what would be the use case of keeping references in the `medias` table if actual files are deleted!

As for force deleting `medias` records, I'm assuming you do that programmatically in your project, since Twill's UI does not offer that option right now?

It would definitely make sense to delete files when force deleting. It would be on Twill to implement as Laravel's file storage system does not have a direct relationship or even know about records in the database. The `cascade_delete` configuration variable mentioned above could be used there as well.

Thanks,
Quentin

**Comment by nikhiltri** [comment]
Ah! I see those configurations now and see where they're used in the MediaRepository. I was manually purging some content from our DB in tinker using the model directly, so this cascade wasn't taking effect. I'll see if I can use the MediaRepository next time I need to do something like this.

The way you described the logic as it's tied to the UI makes sense. I agree though, that if the file is removed from file storage, it doesn't make sense for its soft-deleted record to sit around in the DB!
