### ISSUE TITLE
Delete media in media library not cascade delete the folder

### ISSUE THREAD

**Issue by yanhao-li** [area17/twill#375]
when `MEDIA_LIBRARY_CASCADE_DELETE=true`
Delete the media from media library will delete the file itself, but not the folder containing it.
Testing it locally with Glide.

**Comment by ifox** [comment]
Hi @yanhaoli, thanks for reporting this. The problem here is that the folder might not necessarily be empty after the file itself is deleted because there might be multiple files in the same uuid folder if multiple files were uploaded at the same time. We need to add a check for emptiness of the uuid folder when deleting the file and if empty we can then delete it. I think this might cause issues with S3 though so would need some testing there because S3 doesn't actually store folders being block storage. Hopefully this is something Flysystem already deals with.

**Comment by ifox** [comment]
It seems like we would need to make sure to include a trailing slash with the uuid for S3 to delete it, which would work as long as it is empty.

See https://github.com/aws/aws-sdk-php/issues/1553#issuecomment-390264492

**Comment by haringsrob** [comment]
Fixed in https://github.com/area17/twill/pull/1579
