### ISSUE TITLE
Custom block with php

### ISSUE THREAD

**Issue by Insperio** [area17/twill#420]
Hi, is there a Twill way to add php into a custom block ? I want to create a block that will load some more resources from database and remote api (for example weather details based on user location). 

Where should I start ? I couldn't find anything in documentation.

Thanks for any help.

**Comment by ifox** [comment]
Hi @insperio! Since the blocks currently are statically built as Vue components, you cannot add dynamic content to them through PHP. This is something we do have ideas about though. In the meantime, the approach to load dynamic/remote content is to use the `browser` field, since it can load content through an ajax request you can control. However your use case seems different. Can you share more about your example?

**Comment by Insperio** [comment]
@ifox Thanks for your reply ! 
I was hoping to create a custom block that will use front end user location and their travel preferences (db) to find out weather in their location and other preferred locations (php api call / cache). 
I wanted to add it as a custom block so admin can control the placement on pages, change visuals or remove it completely if they don't want it any more.

In summary, as a minimum, I would need some a way to pass php variables into front end template of that custom block (I could get away without showing example data in admin panel).

I hope above helps. Do you have any ideas ? 

Thanks
