### ISSUE TITLE
Previewing with SPA frontend

### ISSUE THREAD

**Issue by nsivertsen** [area17/twill#46]
Hi there! Let me first thank you for releasing Twill to the public. It really raises the bar for CMSs in terms of flexibility and usability. Finally someone has implemented blocks in a sane manner! However, there is one thing I'm unclear on, and I hope you'll allow me to ask a question here.

In the section [Feature list > Developer experience](https://twill.io/docs/#feature-list) of the docs, you say:

> Previewing and side by side comparison of fully rendered frontend site that you’ll get up and running very quickly whatever the way you built your frontend (fully headed Laravel app, hybrid Laravel app with your own custom API endpoints or even full SPA with frameworks like React or Vue)

It is not at all clear to me how one would go about doing so.

Is there a standard way for passing preview data to a separate SPA frontend? How does that work for the individual block views in the editor? Would it require maintaining separate copies of the templates in Blade and my JS framework of choice?

**Comment by ifox** [comment]
Hi @nsivertsen!

Thank you so much for your kind words about Twill!

For sure, any questions is welcome here!

I do not have an example at hand right now to direct you to but I will try to work on it as soon as possible. Internally at AREA 17, we did not implement a true SPA in front of Twill yet, but from some relatively simple experimentations we do think it is possible with all the tools Twill has to offer.

For blocks, exactly, you should be able to boot your SPA and display a standalone component fed with its content from Blade templates. You could, for example, pass props to a component using the `$block` variable that is made available in each of your blocks' render templates, or initialize a global store from there too. 

Using `block_editor` configuration variables, you can set things up to your preference:

```php
'block_editor' => [
    'block_single_layout' => 'site.layouts.block', // Blade layout extended by all blocks templates
    'block_views_path' => 'site.blocks', // Path of blocks's Blade templates
    'block_views_mappings' => [], // Custom views mappings for block types, if the default does not work for you (block type is the name of the Blade view)
    'block_preview_render_childs' => true, // When using repeaters inside blocks, this allow you to render childs in parents if set to false
    ...
]
```

I see many possible approaches, like using the same view for all blocks for example if that's helpful. I guess it really all depends on your SPA architecture.

For full previews, it might be more complex to setup if your SPA solely relies on API requests, as the previewed data is not easily exposed right now because what happens is that the Eloquent model is hydrated from your form submission instead of being saved to database. That hydrated model is then passed to a Blade view (by default, `site.singularModuleName`, but you can customize it using the `$previewView` variable in your module's admin controller). If you're able to fully init state in your app through inline Javascript, for example, it would be much simpler. It should be doable to expose the hydrated model though, but that would mean your SPA needs to be aware of the context (preview or regular rendering) to send the right API request.

I'd be very happy to support you setting things up as this is a really interesting use case for Twill, so please let me know how I can help! Do you have a project in mind that could benefit from Twill?

**Comment by nsivertsen** [comment]
Hi @ifox, thank you so much for your detailed answer!

Those suggestions make sense, but I'll probably have a bunch more questions in the next few days when I get around to trying them.

For full previews, exposing the hydrated model over an API along with a context does sound like a good bit more work than just instantiating it with inline Javascript. Does Twill have the concept of a preview session or anything like that to even make this secure, or would I have to implement that?

Thanks for your offer, I'd be more than willing to contribute back some docs on the topic in return once I've figured everything out. Until then I'll keep on badgering you with questions ;)

Regarding my use case, I started typing out an answer here, but I think that's better suited for an email rather than polluting GH issues, so I'll send you one in a sec, if that's alright?

**Comment by ifox** [comment]
No worries, @nsivertsen! Feel free to send more questions.

Previews in session/secured API is not implemented right now, you would have to implement it using Laravel's features and Twill's flexible architecture. I'm open to discussing approaches here!

Email's definitely alright, thank you so much for sharing!

**Comment by nsivertsen** [comment]
I'm closing this issue, as it was more of a question. I've got a working setup of this for Svelte and Sapper in the frontend for a site that's going live soon. Will update this with some pointers after that. Maybe there could be a "tutorials" section or something like that in the docs for more specific setups like this?

**Comment by ifox** [comment]
That's awesome to hear @nsivertsen, I'm very excited to learn more about your integration with Svelte and Sapper. 

I'm definitely thinking about a guides/tutorials section for our docs. GitHub issues are starting to be a great source of extended documentation for our users, and I think it makes sense to port some of that content over to the docs themselves. I will follow up here once I setup a structure for contributions.

**Comment by rockfreak** [comment]
@nsivertsen  I would be interested how you solved this issue as I'm currently building a twill backend with a SPA head written in vue. 

Trying to work out how to get the previewing function working nicely.

**Comment by rishpandey** [comment]
@nsivertsen Can you share how you did it? I am trying something similar to you with a standalone vue.js app using twill as a backend.

@rockfreak Did you figure it out?

**Comment by simonpeters** [comment]
Any update on this?

Would love to see a tutorial on this.

**Comment by futurewebsites** [comment]
@nsivertsen & @rockfreak I too would be very interested to see if you managed to get this up and running, any help would be greatly appreciated

**Comment by GraxMonzo** [comment]
Hey @ifox, I was wondering if it is possible to do a block preview using Inertia.js?

**Comment by zumbidoweb** [comment]
got it to work with inertia  !!!
create a separed react app only for the editor with the same libraries but without inertia and inject you block props writing with php
in safari there is a issue with the iframe height , but in chrome works great.

block.blade.php
![Screenshot 2022-07-25 at 11 24 35 PM](https://user-images.githubusercontent.com/107581186/180867929-0ad21024-f4de-4229-82e6-17bb467b1827.png)

text.block.php
![Screenshot 2022-07-25 at 11 24 42 PM](https://user-images.githubusercontent.com/107581186/180868034-f768a1cf-e930-4cf9-bae3-c665c69c721e.png)

editor.js
![Screenshot 2022-07-25 at 11 24 29 PM](https://user-images.githubusercontent.com/107581186/180868091-4cb6c8f0-cd56-4c17-93a6-c004ca1ea5ae.png)
