### ISSUE TITLE
Unable to get blocks to work

### ISSUE THREAD

**Issue by sebastianlenton** [area17/twill#48]
Hi,

I'm using Twill 1.2 & Laravel 5.7 in Homestead.

I implemented the example code in the documentation under "Adding Blocks", I added the Quote block as described. All seemed to go well, but there are no textareas inside them so I can't enter any text:

![screen shot 2018-10-24 at 19 14 47](https://user-images.githubusercontent.com/1895476/47452068-3608b380-d7c1-11e8-8b84-d02b7b8006b8.png)

I guess (I'm not very experienced with Vue, sorry!) that the Vue components inside the blocks aren't rendering, as I can still see the a17-block-quote tags within the blocks in the devtools inspector?

I've gone through the steps in the docs several times, from a fresh install also, and can't work out what the problem is. I'd very much appreciate it if you could take a look, an example can be found at https://github.com/sebastianlenton/twill-test

Thanks,
Seb

**Comment by ifox** [comment]
Hi Seb!

I just cloned and setup your example project and got blocks to render without changing anything actually.

<img width="942" alt="screen shot 2018-10-24 at 2 33 39 pm" src="https://user-images.githubusercontent.com/708498/47453096-d4811e80-d799-11e8-8f10-8de10bb5559b.png">

But this is a case of "it works on my computer", you know. The issue is, and this has been a recurring issue that we are aware of and actually have a plan forward to avoid, environment differences with npm  scripts execution. The `twill-copy-blocks` one makes use of the `cp` command, with parameters and directories patterns that are not environment agnostic. We are working on phasing out those npm scripts for a simpler `artisan` command that won't be affected by developers/servers environments.

In the meantime, please try the following `twill-copy-blocks` script to replace the one you took from the documentation and let me know if it is working for you:

```
"twill-copy-blocks": "npm run cms-clean-blocks && mkdir -p resources/assets/js/blocks/ && mkdir -p vendor/area17/twill/frontend/js/components/blocks/customs/ && cp -R resources/assets/js/blocks/* vendor/area17/twill/frontend/js/components/blocks/customs/"
```

**Comment by sebastianlenton** [comment]
Thanks very much for responding so quickly.

I replaced it in package.json and ran **npm run twill-build**, and got the error "missing script: cms-clean-blocks" - should it be "twill-clean-blocks" in that script?

**Comment by ifox** [comment]
My bad, yes, sorry about that:

```
"twill-copy-blocks": "npm run twill-clean-blocks && mkdir -p resources/assets/js/blocks/ && mkdir -p vendor/area17/twill/frontend/js/components/blocks/customs/ && cp -R resources/assets/js/blocks/* vendor/area17/twill/frontend/js/components/blocks/customs/"
```

**Comment by sebastianlenton** [comment]
Hi,

Thanks very much for the fix- the block worked correctly after replacing the script and running **npm run twill-build** again.

However, I'm finding I have to run this every time I create a new block, and it takes 10-15 minutes for the script to complete in Homestead on my machine.

Is there anything I can do about this?

Thanks again,
Seb

**Comment by ifox** [comment]
Running locally should make it <5 minutes, but in that context, you want to use the dev script that inject changes in a few seconds maximum.

**Comment by sebastianlenton** [comment]
Looks like I've managed to get HMR working correctly now.

Thanks again for your help and patience.

**Comment by arkid** [comment]
@ifox can you clarify what dev script you are referring to ?
