### ISSUE TITLE
Major problem re hot module replacement (npm run twill-dev)

### ISSUE THREAD

**Issue by sebastianlenton** [area17/twill#49]
Hi,

I ran npm run twill-dev to start the HMR server. It didn't seem to work (may raise a separate issue re this) but more importantly, all my CSS and JS assets are now being served from localhost:8080 rather than admin.mysite.localhost:8000, meaning that none of them load.

I've rebooted the VM but it still persists. How do I revert this?

Thanks,
Seb

**Comment by ifox** [comment]
Hi,

This is a Laravel Mix related issue, please try to delete the `hot` file in your project's `public` directory. This is normal behavior that it serves assets on localhost:8080, it is Webpack HMR. Note that to make things easier on your end, you should run this locally, not in the VM, otherwise you would have to figure out port mappings.

**Comment by sebastianlenton** [comment]
Hi,

Fixed, thanks! Sorry, I'm a little out of my comfort zone and read some misleading advice elsewhere re running this in the VM.

Thanks again.
