### ISSUE TITLE
Getting repeaters in contentFields section to save

### ISSUE THREAD

**Issue by sebastianlenton** [area17/twill#51]
Hi,

I managed to successfully add a repeater block (the "accordion" example as per the docs)- that works correctly. Following that, I attempted to add a repeater to the contentFields section, but I can't get it to save its data on update.

My CRUD module is called Projects. I added the repeater to projects/form.blade.php below my description field:
```
@section('contentFields')
    @formField('input', [
        'name' => 'description',
        'label' => 'Description',
        'maxlength' => 100,
        'required' => true,
    ])

    @formField('repeater', [
      'name' => 'myRepeater',
      'type' => 'accordion_item']
    )
@stop
```

I also added 'myRepeater' to the Project model fillable array, and added a json column called 'myRepeater' to the migration file (not sure whether this is correct, the docs seem a bit sparse re this).

The repeater appears correctly on the edit screen, and I can add items and text, but none of it saves to the database on update. What am I missing here?

Thanks
Seb

**Comment by ifox** [comment]
Hi @sebastianlenton!

Another instance of our documentation not being super clear on how those kinds of fields/relationships get saved by default, sorry you're running into it, but thanks for the feedback, that's definitely really helpful for us.

You probably noticed that blocks automatically save and retrieve their content, whatever the fields you use in there. That's because blocks' contents are stored into Twill's provided `blocks` table in a JSON column.

Anything outside of the block editor typical works following Laravel's relationship conventions. For a repeater, this means a `hasMany` relationship. In your case, the `Project` model would need a relationship defined with another Eloquent model, AccordionItem. In this other model, you would define fillables and other properties exactly as if accordion items were a Twill module in itself. Of course, this means having a `project_id` foreign key in your `accordionitems` table. Finally, you'd need to use helpers provided in the `HandleRepeaters ` repository trait to actually save and retrieve those items:

```php
// in afterSave
$this->updateRepeater($object, $fields, 'relationName');

// in getFormFields
$fields = $this->getFormFieldsForRepeater($object, 'relationName');
```

Technically, nothing really prevents you from saving repeaters content in a column of the same model, but you'd have to implement some custom logic in your repository.

You can also reuse the same repeater in multiple models, using a polymorphic table and `belongToMany` relationships.

**Comment by sebastianlenton** [comment]
Hi,

Thanks for getting back re this. Would you mind going into more detail re exactly how to implement this? I've had a go but not been able to get it to work (pardon my inexperience).

I've committed my attempt to https://github.com/sebastianlenton/twill-test if that might be useful.

Thanks again,
Seb

**Comment by ifox** [comment]
Hey Seb,

Here's a diff of how I got your repeater to work: https://gist.github.com/ifox/0981ab68701500ff6a2604b5a8db2949

And here's what I did:
- Added custom table name for `AccordionItem` model, because of how Laravel expect it by default
- Renamed `title` field to `header` in AccordionItem model to align with repeater form field name
- Added `project_id` in AccordionItem fillables
- Removed `additionalRemark` from `Project` fillables as it was creating an error for me (column is missing from migrations I guess)
- Renamed repeater type in twill.php to plural form (like the relationship)
- Renamed `accordionItems` relationship to use underscore like repeater type
- Fixed `hasMany` call with correct reference to AccordionItem model
- Imported `HandleRepeaters` in `ProjectRepository`
- Added `getFormFields` to `ProjectRepository` to retrieve accordion items using provided helpers
- Updated call to `updateRepeater` helper to make it work with custom naming
- Fixed `accordion_item` table migration (replace title by header)
- Updated reference to repeater type in form

**Comment by sebastianlenton** [comment]
That worked perfectly! Thank you very much for looking into this and providing such a detailed response. Hopefully I can re-use this pattern to add other repeaters.
