### ISSUE TITLE
Moving menu-items from 1 menu to another breaks the menu in the backend

### ISSUE THREAD

**Issue by melcarthus** [area17/twill#667]
Using twill 2.2.1

A site we are building with twill has a couple of menu's defined.
The primary menu's are primary-menu and secondary-menu. When we move a sub-menu-item from 1 menu to the other the parent ID is not removed if the previous item was a sub-menu item. This will break the whole menu in the backend an editing of the menu cannot continue until the menu item causing the problem is deleted.

As of now moving between menu's is not possible. You have to remove the item and just add it again in the menu you want.

**Comment by ifox** [comment]
Hi @melcarthus, sorry we haven't been responding to you earlier on this. You may have moved on since then, but if not, I'd invite you to try the new HasNesting trait and review the new documentation in #1140, as I'm assuming you were talking about a module that was using the nested-set approach. It sounds like your issue may have been that you didn't queue the tree updates.
