### ISSUE TITLE
$browserColumns not working

### ISSUE THREAD

**Issue by milewski** [area17/twill#75]
Hi im facing another bug... 

I have a `CityController` and a `SubjectController` i show the cities inside a `browser` field on the Subject Create/Edit page, however i have modified the "default" `title` field to `name` on the city model and added the `$titleColumnKey = 'name'` on the `CityController`, it displays correctly on the browser listing, however after saving, and refreshing the page the "titles" display as blank field here is an example:

After picking the cities and hiting `Save as Draft`

![image](https://user-images.githubusercontent.com/2874967/48271822-3028f880-e478-11e8-8148-527e9b98fff9.png)

After Refreshing the page (note that the 2 records are present and persisted to db, if i manually edit the database and add a column called title: and set to `hello world`, it will display correct here)
![image](https://user-images.githubusercontent.com/2874967/48271846-3cad5100-e478-11e8-80ca-eb3743a3551d.png)

I see the correct "title"/name on the browser listing
![image](https://user-images.githubusercontent.com/2874967/48272421-7f235d80-e479-11e8-9c1b-8aa4f20f12b8.png)

i have also tried adding this to `CityController`:

```php
protected $browserColumns = [
    'title' => [
        'title' => 'name',
        'field' => 'name',
    ],
    'name' => [
        'title' => 'name',
        'field' => 'name',
    ]
];
```

This is the response i get from navigating to `http://localhost:9090/admin/pages/cities/browser`

```json
{
    "data": [
        {
            "id": 2,
            "name": "Rio de Janeiro",
            "edit": "http://localhost:9090/admin/pages/cities/2/edit"
        },
        {
            "id": 1,
            "name": "Sao Paulo",
            "edit": "http://localhost:9090/admin/pages/cities/1/edit"
        }
    ]
}
```

but looks like the frontend still expecting a field named `Title` to be present into the response in order for it to work... any suggestion?

**Comment by ifox** [comment]
Hi @milewski,

I assume you are using the `getFormFieldsForBrowser` helper in the `getFormFields` hook of your repository, right?

If so, using your example, `getFormFieldsForBrowser($object, 'cities', 'pages', 'name')` should do the trick! The fourth parameter allows you to provide a different column name than `title` to display in already attached items. Another way to go about it is to provide a `titleInBrowser` accessor on your model (`getTitleInBrowserAttribute()`).

Regarding `$browserColumns`, yes, this is a regression following our complete FE revamp using Vue. It used to display more columns in the modal and fields if specified. I'm labelling this issue as a bug so that we can restore functionality as soon as possible there.

**Comment by milewski** [comment]
Hi @ifox, 

Thanks!! both ways worked:

```php
//model
public function getTitleInBrowserAttribute()
{
    return $this->name;
}
```
and

```php
//repository
public function getFormFields($object) {

    $fields = parent::getFormFields($object);

    $fields['browsers']['cities'] = $this->getFormFieldsForBrowser($object, 'cities', 'pages', 'name');

    return $fields;

}
```
👍

**Comment by arkid** [comment]
Please get $browserColumns working again, that would be very useful as a shortcut to this functionality...   +1

**Comment by nedbaldessin** [comment]
👋 Just wanted to bump this issue, that I had to work around too. In my case, the browser is in a block. I had to add a bunch of accessors in the model: `defaultCmsImage`, `getAdminEditUrlAttribute`, and `getTitleInBrowserAttribute`. Thanks.

**Comment by pboivin** [comment]
Hi everyone, took some time to revisit this issue. I just wanted to confirm what is or isn't an issue anymore.

### 1. `name` instead of `title`

Both suggestions from @ifox worked for me. There's also a third solution now through the `$browsers` property in the repository:

```php
class PostRepository extends ModuleRepository
{
    protected $browsers = [
        'authors' => ['titleKey' => 'name']
    ];
    
    // ...
}
```

### 2. `$browserColumns`

This is one is also working for me. I was able to add extra columns in the browser modal:

```php
class AuthorController extends BaseModuleController
{
    protected $moduleName = 'authors';

    protected $titleColumnKey = 'name';
    
    // ...

    protected $browserColumns = [
        'name' => [
            'title' => 'Name',
            'field' => 'name'
        ],
        'test' => [
            'title' => 'Test',
            'field' => 'test'
        ],
    ];
}
```

@arkid, were you trying to add columns inside the actual browser field, in the form?


### 3. Attribute accessors

@nedbaldessin, I could not fully replicate this issue with a browser field inside a block. The only accessor that was required was `getTitleInBrowserAttribute`, but not `defaultCmsImage` and `getAdminEditUrlAttribute`. Is there any other information you could share to replicate this?

<br>

Thanks and sorry for the late reply.
