### ISSUE TITLE
Media Library upload fails when iconv does not support transliteration

### ISSUE THREAD

**Issue by milewski** [area17/twill#78]
Hi, im trying to upload images im facing this problem:

```
{ "type": "ErrorException", "message": "iconv(): Wrong charset, conversion from `UTF-8' to `ASCII//TRANSLIT' is not allowed", "file": "/home/vendor/area17/twill/src/Helpers/media_library_helpers.php", "line": 28 }
```

![image](https://user-images.githubusercontent.com/2874967/48333178-62fa0900-e691-11e8-89a1-526a80f1c908.png)

it certainly has something to do with my environment.. as im running php inside an alpine linux docker container, i do have all necessary "laravel" dependencies installed. including the `iconv` extension, but yet it doesnt seem to work on an alpine linux, the hacks i have seem online seens very insecure to have set in a production server later.. this issue is all caused due to this function:

```php
function replaceAccents($str){
  return iconv('UTF-8', 'ASCII//TRANSLIT', $str);
}
```

my quickly workaround is to redefine this function, perhaps consider using http://php.net/manual/en/class.transliterator.php with intl extension to do these accent replacement?

**Comment by tomascardenal** [comment]
More on this- I get a similar error on the same line. While on OSX, if i input a filename with accents or the "ñ" character, i get this exception. "type": "ErrorException", "message": "iconv(): Detected an illegal character in input string", "file"... etc

 I tested the iconv() function on itself, hardcoding strings with those same characters (on a visual aspect) seem to generate no exceptions. Then I analyzed the strings giving me issues against those without issues and found that THESE are the guity characters:

́ | U+0301 | COMBINING ACUTE ACCENT 

̃ | U+0303 | COMBINING TILDE

I'm guessing there's an issue in general with combining characters and the vicon() function. Since characters like "U+00F3 | LATIN SMALL LETTER O WITH ACUTE" are replaced without any issue.

**Comment by ifox** [comment]
Closing this as there hasn't been any activity in a long time. If you are still looking for a fix for this, feel free to let us know.

**Comment by pboivin** [comment]
Updating this for future reference. A possible fix was found by `@FourStacks` on Discord :

```php
if (!function_exists('replaceAccents')) {
    /**
     * @param string $str
     * @return bool|string
     */
    function replaceAccents($str)
    {
        return mb_convert_encoding($str, 'ASCII', 'UTF-8');
    }
}
```

https://discord.com/channels/811936425858695198/811986149064441927/918893543999807590

**Comment by tudor-sv** [comment]
@pboivin , you saved my life. Mega-Thanks!

**Comment by tudor-sv** [comment]
It would be rally nice if the maintainers would replace iconv with mb_convert_encoding. It's been 4 years and mbstring is a required extension for Laravel anyway.
