### ISSUE TITLE
Incorrect default locale max-length

### ISSUE THREAD

**Issue by milewski** [area17/twill#80]
The default locale column when using the `createDefaultTranslationsTableFields` helper function is of length 6, however 

```php
function createDefaultTranslationsTableFields(...)
{
    ...
    $table->string('locale', 6)->index();
    ...
}
```

However on the `area17/twill/src/Helpers/i18n_helpers.php:53` `zh-Hans` is 7 char long... causing the following error on create/update

```
error: {type: "Illuminate\Database\QueryException",…}
file: "/home/vendor/laravel/framework/src/Illuminate/Database/Connection.php"
line: 664
message: "SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'locale' at row 1 (SQL: insert into `exchange_type_translations` (`locale`, `active`, `title`, `exchange_type_id`, `updated_at`, `created_at`) values (zh-Hans, 1, Demo, 2, 2018-11-13 05:35:34, 2018-11-13 05:35:34))"
type: "Illuminate\Database\QueryException"
```

Thats an easy fix, however i am wondering if it would make sense to have this mapping abstracted to the twill.php or somewhere else so it can be configured.. as for instance i need `zh-Hans` to map to `中文` instead of `Chinese (simplified)`, when my global application language is set to EN, and vice versa.... my quickly solution meanwhile is by overriding that function...

**Comment by ifox** [comment]
Hi Rafael,

thanks for reporting this too!

Definitely a lack of testing here... but the idea with this function being a global helper is actually that you can override it in your own application, simply because I don't think we can cover every user needs around languages. The setup you're trying to achieve should work using Laravel translations files.

I like the idea of providing configuration through `twill.php` though, thanks for your suggestion!
