### ISSUE TITLE
Special characters in input placeholder break edit form

### ISSUE THREAD

**Issue by daun** [area17/twill#809]
When setting a placeholder on a text input that contains a single-quote `'`, the whole edit form breaks and the page comes up empty but without errors.

Double-quotes work fine, using `htmlspecialchars` or similar has no impact.

The best temporary fix I found is replacing single-quotes with apostrophes:

```blade
@php
    // Replace apostrophes to avoid quotes (') breaking the edit form
    $title = $item->title ?? '';
    $title = str_replace("'", "ʼ", $title);
@endphp

@formField('input', [
    'name' => 'title_formatted',
    'label' => 'Formatted title',
    'type' => 'textarea',
    'placeholder' => $title,
    'rows' => 2
])
```

**Comment by ptrckvzn** [comment]
Hi @daun,

I did a quick test and the `input` partials that `formField` calls is escaping most value (including placeholder). This is done for safety, but if you need to pass an unescaped string to the placeholder value, you could copy the view to your project and use `{!! $placeholder !!}` to allow special characters instead of `{{ $placeholder }}` in use now.

The file: `https://github.com/area17/twill/blob/2.x/views/partials/form/_input.blade.php#L52`

You could make a copy in your project `resources/views` folder at `admin/partials/form/_input.blade.php` and change, on line 52 the double curly brackets to `{!! $placeholder !!}`.

Closing this now, but feel free to reply if it doesn't work.

**Comment by daun** [comment]
@ptrckvzn Can we reopen the issue? The problem isn't that things are escaped when I want them unescaped. The problem is that certain characters like `'` are **not** escaped, completely breaking the form. The whole edit page will show up empty with no exception, console error or anything to indicate that something went wrong. Just the usual header, navigation, and then no form. The Vue app at some point cancels rendering, deleting the `#app` root element. It took me 4 hours to even find out what the problem was. That's what I'm trying to solve.

**Comment by ptrckvzn** [comment]
@daun Sorry to hear that! Would you mind sharing a bit more about your environnement? Which Twill and Laravel version are you using?

I tested it against the 2.x branch (Laravel 7.30.4) and when I pass a $title string with an apostrophe without any replacement, it comes out as `&#039;`.

I did try something else, using single-quotes to enclose the placeholder in `_input.blade.php` (`placeholder='{!! $placeholder !}}'`and replacing single quotes in your title string with the html `&#39;`. 

```
$title = str_replace("'", "&#39;", $title);
```

At the moment, in the 2.x branch, (I believe) the placeholder attributes is escaped by blade and is passed to the Vue component which doesn't decode them.

**Comment by daun** [comment]
@ptrckvzn I have a hunch that it's related to translated fields. They pass the data as JSON to the a17-locale component which would change how it should be escaped. I'll check the exact environment later.

**Comment by daun** [comment]
@ptrckvzn Indeed, the `str_replace` solution is the one I settled on for now, but ideally there's a fix we can apply upstream. Probably by using `htmlspecialchars` or `json_encode` directly when passing the props into the `a17-locale` component.

**Comment by haringsrob** [comment]
This is solved in https://github.com/area17/twill/pull/1621
