### ISSUE TITLE
Getting a repeater in contentFields section to render on the front-end

### ISSUE THREAD

**Issue by sebastianlenton** [area17/twill#81]
Hi,

I successfully added a repeater of media & input fields to the contentFields section of a CRUD module (as per the process at https://github.com/area17/twill/issues/51), but I can't work out how to pull it into the front end in order to render the contents.

If you could advise, that would be fantastic. FYI you can find my code at https://github.com/sebastianlenton/twill-test if that helps (the module in question is called "experiments").

Thanks again,
Seb

**Comment by ifox** [comment]
Hi Seb,

cool! I will test your project later today, but in the meantime, you should be able to access the repeaters content like any other relationship: `$experiment->experimentimages()` should return a collection of `Experimentimage` models, for which you can use regular model helpers for images etc.

You might be having issues because of naming conventions though, as by default multi-words models in Laravel should use PascalCase. I'll give your project a try and will let you know.

**Comment by sebastianlenton** [comment]
I solved this! https://github.com/area17/twill/issues/82 gave me the solution. Thanks again!
