### ISSUE TITLE
How to translate media

### ISSUE THREAD

**Issue by AntoineGermain** [area17/twill#84]
Hello,

I have a model in 3 language, and i need a specific media for each language.

Is it possible ? if so, how ? :)

Thank you !

**Comment by ifox** [comment]
Hi Antoine!

I'm sorry but it isn't at the moment. Assuming that your list of languages is still controlled in code, you could use 3 different fields.

But I definitely see how unscalable that could become and technically it wouldn't be complicated to implement (the file field actually support language dependant attachment), so thanks for sharing your need here, we'll make sure to add it to our backlog of ideas for new features.

**Comment by newvladimirov** [comment]
@ifox hi! Why do you think it could become unscalable? I'm almost done with that and thought about pull request. Is it possible or you don't want to see this feature for now?

**Comment by ifox** [comment]
Hi @newvladimirov, sorry for the delay here, I'm reviewing all issues now that 1.2.1 is out and can't remember reading your question before!

I meant manually creating an image field for each language could become a problem, not implementing a translatable medias field, which is actually something we definitely need and should work fine like the files field.

Feel free to submit a pull request if you can, that would be awesome, but otherwise I'll look into implementing it soon.

**Comment by ifox** [comment]
This is now available in Twill 1.2.2 using the new configuration key `twill.media_library.translated_form_fields`.
