### ISSUE TITLE
Files and Medias doesnt work with repeater/block_editor?

### ISSUE THREAD

**Issue by milewski** [area17/twill#85]
Hi, im facing a blocking issue... 

```php

@formField('files', [
    'name' => 'video',
    'label' => 'Video',
])

@formField('medias', [
    'name' => 'image',
    'label' => 'Image'
])

@formField('input', [
    'name' => 'test',
    'label' => 'Test'
])

...all the other input types

```

The `@formField('files')` and `@formField('medias')` doesn't work inside a `block_editor`and as a `repeater`, every other field get persisted to the db... is it due that medias and files are currently unsupported? or am i misconfiguring something? all my related files has the correspondents traits on model and repository but yet these doesn't seem to work

![untitled-1](https://user-images.githubusercontent.com/2874967/48613678-678f2c00-e9c7-11e8-8e31-f22d1498521c.png)

**Comment by milewski** [comment]
and im getting these error on the console whenever i try to attach an image.. maybe its related

![image](https://user-images.githubusercontent.com/2874967/48614778-09b01380-e9ca-11e8-82d9-75d33513b07e.png)

**Comment by milewski** [comment]
Well the console log issue is not related ... it was due that `MediaField.vue` is appending a `&no-cache` which results to a `http://something.com/assets/image.jpg&no-cache` which is 404 

`MediaField.vue:463`

```diff
-this.img.src = this.media.thumbnail + '&no-cache'
+this.img.src = this.media.thumbnail + '?no-cache'
```

**Comment by ifox** [comment]
Hi @milewski!

Files and medias fields are supported in the block editor.

However, any medias or files field you add to a block needs its own configuration in `config/twill.php`, similarly to `mediasParams` and `filesParams` in models. Since Block is a model inside the Twill codebase and it's nature is completely dynamic, that configuration happens in the global configuration file.

The `block_editor` configuration array should have a crops key with a array of medias cropping configuration, and a files key with an array of file field names.

You can see an example [here](https://twill.io/docs/#default-configuration). That's definitely an area of the documentation we need to improve.

**Comment by ifox** [comment]
Regarding the console errors, good catch! Our local image rendering service is pretty dumb right now as you might have noticed and no parameters are applied to image urls, which produces this error on your end. We should make sure to append with ? if no parameters are existing on the image url instead of using & by default.

We are actually implementing a Glide powered service right now, to avoid enforcing our users into Imgix when they need images transformations. Our local rendering service is definitely not production ready for that matter as it is not applying any transformation whatsoever, it just returns the original file, and that's why Imgix is the recommended service at the moment.

**Comment by ifox** [comment]
Yup, sorry for the confusion, and thanks for your feedback, getting an external view on things is super helpful to improve our docs.
