### ISSUE TITLE
Physically remove uploaded images

### ISSUE THREAD

**Issue by awgul** [area17/twill#97]
Hey,

I set `MEDIA_LIBRARY_CASCADE_DELETE` to `true`.
But now I can only mark multiple images (earlier I could mark only one image).
And when I hit delete the images are not physically deleted at all.

This `MEDIA_LIBRARY_CASCADE_DELETE` is working here like: select multiple files or not.

I use endpoint_type: local.

**Comment by ifox** [comment]
Hi @awgul!

There are no relationship in code between `MEDIA_LIBRARY_CASCADE_DELETE` and being able to select multiple images in the media library. Are you sure you were in 2 different contexts when testing that? Like once by opening the media library from the navigation, and once by opening the media library through a medias form field. When you open it from the navigation, you're able to select multiple, but if you're coming from a Add image button on a medias form field, you're only able to select one image, since you're trying to attach it to the form, not manage your collections of images.

Regarding the files not being deleted, I'll check on my end and will get back to you but this should definitely be the case when set to true.

**Comment by ifox** [comment]
Hey @awgul, same here, closing to focus on fixing all related issues in #173. Thanks!
